### ISSUE TITLE
[website] Language Reference link broken.

### ISSUE THREAD

**Issue by ekipan** [Mark-Wills/TurboForth#1]
Not a TurboForth issue but a website issue: the link to the [language reference](http://turboforth.net/lang_ref/language_reference.asp) from turboforth.net is currently broken.

**Comment by Mark-Wills** [comment]
Thanks I've got the tech support looking at it!

Mark

**Comment by Mark-Wills** [comment]
Ok, should be fixed now - thanks again for pointing it out.

Mark

**Comment by ekipan** [comment]
Thank you for getting it fixed :+1:
